### ISSUE TITLE
Dead links and not uniform user interface

### ISSUE THREAD

**Issue by ghost** [mas2g2/RJI-CS4320-Project#5]
List of known dead links by page

Homepage
- site logo (top left)
- site name (top left)
- about us (hamburger icon)
- rating boxes (carousel)

Photo Gallery
- upload images (navbar)
- view images (navbar)
- home button (navbar)
- logo (top left navbar)
- sign in button (top right navbar)

navbar is not consistent across site

**Comment by Christoph5782** [comment]
Navbar is consistent across the site, all links now work!
