### ISSUE TITLE
Rating system is slow on large batches

### ISSUE THREAD

**Issue by ghost** [mas2g2/RJI-CS4320-Project#6]
After running multiple tests, we've concluded that uploading more images takes more time to process and rate. The current bottleneck in the system is the image-quality-assessment subsystem. Now that we have expanded the available RAM in the system, we may be able to utilize the batch functionality instead of sending images one at a time. This will force us to restructure our folder management on the server.

**Comment by ghost** [comment]
adding more server storage should enable us with the capability to implement batch assessment of images on the nerual net

**Comment by sgoggins** [comment]
I did try to upload a folder of images and it did not seem to do anything.  Rating a single image worked, though!

![image](https://user-images.githubusercontent.com/379847/57308265-a87d1900-70ab-11e9-9f6f-df65535854e5.png)

**Comment by sgoggins** [comment]
UPLOADING two photos at a time also seemed to work. It seems that sometimes I get to choose a directory, and other times multiple photos? Or maybe I misremember. 

![image](https://user-images.githubusercontent.com/379847/57308548-30632300-70ac-11e9-8d6b-edbf9faa9237.png)

**Comment by ghost** [comment]
Adding more RAM and another Volume of storage now allows for faster uploads and more of them
