### ISSUE TITLE
Many links are hard-coded

### ISSUE THREAD

**Issue by ghost** [mas2g2/RJI-CS4320-Project#7]
After a thorough review of the existing codebase, we found that our system has many hard coded links on every page. The links are used for images, routing, css files and more. The biggest issue is that they are hard-coded to our current url. If that url were to change, then we would have to update those links on every page. We can fix this issue by utilizing Flask's url tools to make every link for pages, images, css files, js files, etc. all dynamic.

**Comment by Christoph5782** [comment]
All links to stylesheets, scripts, other webpages, images, and favicons that are being hosted on our server have been updated to relative links. This issue should be resolved!

**Comment by ghost** [comment]
Some hard-coded links remained on the back-end app.py, those have been made dynamic
